### PR TITLE
YDA-4954: enable deploying Yoda based on tags

### PR DESCRIPTION
**Pull request by stsnel**
Also ensure that tag/branch checks work in check mode as well.

### CODE REVIEW

**Comment by lwesterhof** [comment]
LGTM

**Review by fiberbit — CHANGES_REQUESTED** [review]
On Linux it should be "git rev-parse HEAD", the ref name is case-sensitive and "head" won't be found.

The part 'grep " refs/tags/"' searches indeed for tags, but branches should also be included, they are onder "refs/heads". With this version branches won't generally be found, and with yoda_version a branch name it will fail.

**Comment by lwesterhof** [comment]
> The part 'grep " refs/tags/"' searches indeed for tags, but branches should also be included, they are onder "refs/heads". With this version branches won't generally be found, and with yoda_version a branch name it will fail.

The check for branches is done in an earlier task. We could combine the two.

**Comment by fiberbit** [comment]
Note that the check for annotated tags in its current form won't always work when more than one annotated tag points at the same commit. Here I've added (only temporarily in my own copy) two annotated tags to the same commit. Note that "git describe --tags" will only see one.

```
marco@dagobah:~/src/yoda (release-1.8)$ git log \-\-oneline -1
34e2e6a5a9b4 (HEAD -> release-1.8, tag: v1.8.5b, tag: v1.8.5a, tag: v1.8.5, tag: v1.8.4, origin/release-1.8) Merge branch 'development' into release-1.8
marco@dagobah:~/src/yoda (release-1.8)$ git describe --tags
v1.8.5b
```

Sorry about the brain-dead formatting of GitHub. There is supposed to be some escape code for that. Jira and Teams have the same "feature". The "oneline" is a long option to git-log and is preceded by two dashes ('-'). But here it triggers strike-through formatting...

**Comment by fiberbit** [comment]
As for "allowing uncommitted changes", this version doesn't check for a "dirty" repository so it allows it anyway.

**Comment by stsnel** [comment]
@fiberbit @lwesterhof Thanks for the feedback. This updated version addresses the issues with multiple annotated tags, capitalization, and combines the three checks (branch, lightweight tag, annotated tag) into two (branch + lightweight tag, lightweight + annotated tag).

**Comment by lwesterhof** [comment]
LGTM

**Pull request merged**
